export const Songs = [
    {
        id: 0,
        title: "More",
        author: "Natan Chaim, Asketa",
        cover: "/covers/More.jpg",
        decription: `Song: Asketa & Natan Chaim - More [NCS Release] Music provided by NoCopyrightSounds Free Download/Stream: http://ncs.io/more Watch: http://ncs.lnk.to/moreAT/youtube`,
        song: "/audio/Asketa & Natan Chaim - More [NCS Release].mp3",
    },
    {
        id: 1,
        title: "Keep Me Closer",
        author: "Low Mileage",
        cover: "/covers/Keep Me Closer.jpg",
        decription: `Song: Low Mileage - Keep Me Closer [NCS Release] Music provided by NoCopyrightSounds Free Download/Stream: http://ncs.io/keepmecloser Watch: http://ncs.lnk.to/keepmecloserAT/youtube`,
        song: "/audio/Low Mileage - Keep Me Closer [NCS Release].mp3",
    },
    {
        id: 2,
        title: "Fall Too Deep",
        author: "Barmuda, Andrew A",
        cover: "/covers/Fall Too Deep.jpg",
        decription: `Song: Andrew A - Fall Too Deep (feat. Barmuda) [Arcade Release] Music provided by NoCopyrightSounds Free Download/Stream: http://ncs.io/falltoodeep Watch: http://ncs.lnk.to/falltoodeepAT/youtube`,
        song: "/audio/Andrew A - Fall Too Deep (feat. Barmuda) [NCS Release].mp3",
    },
    {
        id: 3,
        title: "WATEVA, Thorne",
        author: "What I Say - Thorne Remix",
        cover: "/covers/WATEVA, Thorne.jpg",
        decription: `Song: WATEVA - What I Say (Thorne Remix) [NCS Release] Music provided by NoCopyrightSounds Free Download/Stream: http://ncs.io/whatisayrmx Watch: http://youtu.be/z5j3Q2CfA3M`,
        song: "/audio/WATEVA - What I Say (Thorne Remix) [NCS Release].mp3",
    },
    {
        id: 4,
        title: "Can't Break Me Down",
        author: "PHI NIX",
        cover: "/covers/Can't Break Me Down.jpg",
        decription: `Song: PHI NIX - Can't Break Me Down [NCS Release] Music provided by NoCopyrightSounds Free Download/Stream: http://ncs.io/cantbreakmedown Watch: http://youtu.be/`,
        song: "/audio/PHI NIX - Can't Break Me Down [NCS Release].mp3",
    },
    {
        id: 5,
        title: "A Mere Blip In Your Timeline",
        author: "OBLVYN",
        cover: "/covers/A Mere Blip In Your Timeline.jpg",
        decription: `Song: OBLVYN - A Mere Blip In Your Timeline [NCS Release] Music provided by NoCopyrightSounds Free Download/Stream: http://ncs.io/timeline Watch: http://youtu.be/`,
        song: "/audio/OBLVYN - A Mere Blip In Your Timeline [NCS Release].mp3",
    },
    {
        id: 6,
        title: "Heaven Knows",
        author: "Vizzen, Protolizard",
        cover: "/covers/Heaven Knows.jpg",
        decription: `Song: Vizzen & Protolizard - Heaven Knows [NCS Releases] Music provided by NoCopyrightSounds Free Download/Stream: http://ncs.io/HeavenKnows Watch: http://youtu.be/`,
        song: "/audio/Vizzen & Protolizard - Heaven Knows [NCS Release].mp3",
    },
]

